### ISSUE TITLE
Can u provide an option for no namespace generator

### ISSUE THREAD

**Issue by ubbop42** [avantcredit/gql2ts#229]

**Comment by mikfoo** [comment]
What we did to remove namespace was create our own config file, essentially:

```javascript
// config.js
const {
  DEFAULT_INTERFACE_BUILDER,
  DEFAULT_TYPE_BUILDER,
  DEFAULT_ENUM_TYPE_BUILDER,
  DEFAULT_EXPORT_FUNCTION
} = require('@gql2ts/language-typescript')

const overrides = {
  generateNamespace: (_, interfaces) => `// AUTOMATICALLY GENERATED FILE - DO NOT EDIT

  // tslint:disable

  ${interfaces}

  // tslint:enable
  `,
  interfaceBuilder: (name, body) => DEFAULT_EXPORT_FUNCTION(DEFAULT_INTERFACE_BUILDER(name, body)),
  typeBuilder: (name, body) => DEFAULT_EXPORT_FUNCTION(DEFAULT_TYPE_BUILDER(name, body)),
  enumTypeBuilder: (name, values) => DEFAULT_EXPORT_FUNCTION(DEFAULT_ENUM_TYPE_BUILDER(name, values))
}

module.exports = overrides
```

And then call it like this:

```
gql2ts schema.graphql -e config.js -o schema.ts
```

**Comment by ubbop42** [comment]
Hey,
I tried to do the same, but im already using language-flow, as my -e input file. Is there a way to provide two files or, use this while using language flow.
-Thanks

**Comment by ubbop42** [comment]
> Hey,
> I tried to do the same, but im already using language-flow, as my -e input file. Is there a way to provide two files or, use this while using language flow. And i also would like to know where you stored your config file, because i get file not found error on config.js when running the command.
> 
> `module.js:549
> throw err;
> ^
> 
> Error: Cannot find module 'gql2tsConfig.js'
> at Function.Module._resolveFilename (module.js:547:15)
> at Function.Module._load (module.js:474:25)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at run (/Users/umesh.d/Desktop/graphql-external-api/node_modules/gql2ts/dist/index.js:26:30)
> at Object. (/Users/umesh.d/Desktop/graphql-external-api/node_modules/gql2ts/dist/index.js:53:5)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12`
> -Thanks

I was just being stupid. Thank you.
And foe ppl having the same problem use this -e $(pwd)/gql2tsConfig.js

**Comment by brettjurgens** [comment]
I'm definitely open to a PR adding this option - it seems like a common request
