### ISSUE TITLE
Cannot find namespace

### ISSUE THREAD

**Issue by nomadoda** [avantcredit/gql2ts#236]
Hey! I'm sure I must be doing some rookie mistake, but I'm struggling to get this work.

<details>
<summary>package.json</summary>

```
{
  "dependencies": {
    "@gql2ts/from-schema": "^1.10.1",
    "apollo-server-express": "^2.1.0",
    "graphql": "^0.13.2",
  },
  "devDependencies": {
    "@gql2ts/types": "^1.9.0",
    "@types/graphql": "^14.0.0",
    "@types/node": "^10.10.3",
    "gql2ts": "^1.10.1",
    "ts-node": "^7.0.1",
    "typescript": "^3.0.3"
  }
}
```
</details>
<br />

I'm successfully able to generate the types from my GQL schemas

<details>
<summary>schema.d.ts</summary>

```
// tslint:disable
// graphql typescript definitions

declare namespace GQL {
  interface IGraphQLResponseRoot {
    data?: IQuery | IMutation;
    errors?: Array<IGraphQLResponseError>;
  }

  interface IGraphQLResponseError {
    /** Required for all errors */
    message: string;
    locations?: Array<IGraphQLResponseErrorLocation>;

    /** 7.2.2 says 'GraphQL servers may provide additional entries to error' */
    [propName: string]: any;
  }

  interface IGraphQLResponseErrorLocation {
    line: number;
    column: number;
  }

  interface IQuery {
    __typename: "Query";
    me: IAccount;
  }

  interface IAccount {
    __typename: "Account";
    id: string;
    name: string;
    email: string;
    admins: Array<IAdmin> | null;
  }

  interface IAdmin {
    __typename: "Admin";
    id: string;
    access: Array<string>;

    /**
     * organisation: Organisation
     */
    organisationId: string | null;
    account: IAccount | null;
    accountId: string | null;
  }

  interface IMutation {
    __typename: "Mutation";
    register: IAccount;
    login: IAccount;
    logout: boolean;
  }

  interface IRegisterOnMutationArguments {
    token: string;
    password: string;
  }

  interface ILoginOnMutationArguments {
    email: string;
    password: string;
  }
}

// tslint:enable

```
</details>
<br />

... but when I try to use them in my resolver I run into the following error:

<details>
<summary>resolver.ts</summary>

```
export const resolvers: ResolverMap = {
  Mutation: {
    login: async (parent, { email, password }: ILoginOnMutationArguments, { req }) => {
      // ...
    },
  },
};
```

</details>
<br />
I get the following error when it runs into the resolver:

```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/modules/resolver.ts(32,48): error TS2503: Cannot find namespace 'GQL'.

    at createTSError (./node_modules/ts-node/src/index.ts:261:12)
    at getOutput (./node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (./node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (./node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by brettjurgens** [comment]
@nomadoda I think you might need to add it to your tsconfig via the `typeRoots` option

**Comment by nomadoda** [comment]
@brettjurgens Hm, doesn't seem to solve my issue unfortunately. I added my types folder to the tsconfig `typeroots` which seemed to override some node_modules types. So I included that as well, but I still get the same error.

<details>
<summary>tsconfig.json</summary>

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
    "sourceMap": true,
    "typeRoots": [
      "./src/types",
      "./node_modules/@types"
    ],
    "outDir": "./dist",
    "moduleResolution": "node",

    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "exclude": ["node_modules"],
  "include": ["./src/**/*.ts"]
}
```

</details>

**Comment by yaoyonstudio** [comment]
got the same issue

**Comment by citypaul** [comment]
I'm having the same issue at the moment. I've found I've had to manually change the exported file to go from: 

`define namespace GQL{...`

to

`export namespace GQL{...`

I can then pull this in where required and it does work. It'd be great if I didn't have to do this manually though...

**Comment by shaheermir** [comment]
Having the same issue here. 
Adding it to typeRoots doesn't solve it either. =/

**Comment by enspdf** [comment]
Currently I'm have the same Issue. But It works fine if i use  the 6.0.0 ts-node version, if i upgrade it to the latest version fails.

**Comment by enspdf** [comment]
> I'm having the same issue at the moment. I've found I've had to manually change the exported file to go from:
> 
> `define namespace GQL{...`
> 
> to
> 
> `export namespace GQL{...`
> 
> I can then pull this in where required and it does work. It'd be great if I didn't have to do this manually though...

I try but doesn't work... The same issue happens.

**Comment by sonacy** [comment]
seems that is a ts-node problem.  By default, ts-node does not use files, include or exclude.  If you must use files, enable --files flags or set TS_NODE_FILES=true. so just add --files like: ts-node --files index.ts. works fine to me.

**Comment by enspdf** [comment]
> seems that is a ts-node problem. By default, ts-node does not use files, include or exclude. If you must use files, enable --files flags or set TS_NODE_FILES=true. so just add --files like: ts-node --files index.ts. works fine to me.

Can you show us an example plz ?

**Comment by ankeeth-coditas** [comment]
> seems that is a ts-node problem. By default, ts-node does not use files, include or exclude. If you must use files, enable --files flags or set TS_NODE_FILES=true. so just add --files like: ts-node --files index.ts. works fine to me.

Thanks a ton, man!! This worked for me!

**Comment by juliusdelta** [comment]
@enspdf 
```
// Normal
$ ts-node --files src/index.ts

// Nodemon
$ nodemon --exec ts-node --files src/index.ts
```

@sonacy Thanks for the fix, worked for me.

**Comment by enBonnet** [comment]
> @enspdf
> 
> ```
> // Normal
> $ ts-node --files src/index.ts
> 
> // Nodemon
> $ nodemon --exec ts-node --files src/index.ts
> ```
> 
> @sonacy Thanks for the fix, worked for me.

Thanks @juliusdelta this works to me

**Comment by darkphantomke** [comment]
I installed the older version from current version

// Current
"ts-node": "8.6.2"

// Older
"ts-node": "6.0.0"
